## This file is included as a loop from the deploy-gcs playbook
---
- name: GCS | GD2 Cluster | Add devices | Set facts
  set_fact:
    kube_hostname: "{{ peer.name.split('-')[1]}}"

- name: GCS | GD2 Cluster | Add devices | Add devices for {{ kube_hostname }}
  uri:
    url: "{{ gd2_client_endpoint }}/v1/devices/{{ peer.id }}"
    method: POST
    body: "{ \"device\": \"{{ disk }}\"}"
    body_format: json
    status_code: 201
  register: res
  until: res.status is defined and res.status == 201
  delay: 10
  retries: 50
  loop: "{{ hostvars[kube_hostname].gcs_disks }}"
  loop_control:
    loop_var: disk
